image: ubuntu:latest

stages:
  - deploy

before_script:
  - apt-get update -qq
  - which ssh-agent || ( apt-get install -qq openssh-client )
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - touch ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

# staging-deploy:
#   stage: deploy
#   only:
#     refs:
#       - staging
#   script:
#     - ssh-keyscan -H 45.124.95.234 >> ~/.ssh/known_hosts
#     - bash deploy.sh staging

production-deploy:
  stage: deploy
  only:
    refs:
      - main
  script:
    - ssh-keyscan -H 45.124.95.66 >> ~/.ssh/known_hosts
    - bash deploy.sh main
